// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Interview.Domain.Entities.Models;
using Interview.Persistence.ServiceExtensions;
using Microsoft.EntityFrameworkCore;

namespace Interview.Persistence.Contexts.InterviewDbContext;

public partial class InterviewContext : DbContext
{
    public InterviewContext()
    {
    }

    public InterviewContext(DbContextOptions<InterviewContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Branch> Branches { get; set; }

    public virtual DbSet<Candidate> Candidates { get; set; }

    public virtual DbSet<CandidateQuestion> CandidateQuestions { get; set; }

    public virtual DbSet<CandidateVacancy> CandidateVacancies { get; set; }

    public virtual DbSet<Department> Departments { get; set; }

    public virtual DbSet<JobDegree> JobDegrees { get; set; }

    public virtual DbSet<OpenQuestion> OpenQuestions { get; set; }

    public virtual DbSet<Question> Questions { get; set; }

    public virtual DbSet<QuestionCategory> QuestionCategories { get; set; }

    public virtual DbSet<QuestionLevel> QuestionLevels { get; set; }

    public virtual DbSet<QuestionValue> QuestionValues { get; set; }

    public virtual DbSet<Sector> Sectors { get; set; }

    public virtual DbSet<Vacancy> Vacancies { get; set; }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
#warning To protect potentially sensitive information in your connection string, you should move it out of source code. You can avoid scaffolding the connection string by using the Name= syntax to read it from configuration - see https://go.microsoft.com/fwlink/?linkid=2131148. For more guidance on storing connection strings, see http://go.microsoft.com/fwlink/?LinkId=723263.
        => optionsBuilder.UseSqlServer(ServiceExtension.ConnectionString);

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Branch>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Branch__3214EC07843B0126");

            entity.HasOne(d => d.SectorIdForBranchNavigation).WithMany(p => p.Branches)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_SectorId_forBranch");
        });

        modelBuilder.Entity<Candidate>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Candidat__3214EC07D618580F");
        });

        modelBuilder.Entity<CandidateQuestion>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Candidat__3214EC0751D7778D");

            entity.HasOne(d => d.CandidateIdForCandidateQuestionNavigation).WithMany(p => p.CandidateQuestions)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_CandidateId_forCandidateQuestion");

            entity.HasOne(d => d.QuestionIdForCandidateQuestionNavigation).WithMany(p => p.CandidateQuestions)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_QuestionId_forCandidateQuestion");
        });

        modelBuilder.Entity<CandidateVacancy>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Candidat__3214EC07F10E5675");

            entity.HasOne(d => d.CandidateIdForCandidateVacancyNavigation).WithMany(p => p.CandidateVacancies)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_CandidateId_forCandidateVacancy");

            entity.HasOne(d => d.VacancyIdForCandidateVacancyNavigation).WithMany(p => p.CandidateVacancies)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_VacancyId_forCandidateVacancy");
        });

        modelBuilder.Entity<Department>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Departme__3214EC073207D440");

            entity.HasOne(d => d.BranchIdForDepartmentNavigation).WithMany(p => p.Departments)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_BranchId_forDepartment");
        });

        modelBuilder.Entity<JobDegree>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__JobDegre__3214EC07392F6EFD");
        });

        modelBuilder.Entity<OpenQuestion>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__OpenQues__3214EC07593F38A6");

            entity.Property(e => e.Result).HasDefaultValueSql("((0))");
        });

        modelBuilder.Entity<Question>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Question__3214EC07862B8496");

            entity.HasOne(d => d.OpenQuestionIdForQuestionNavigation).WithMany(p => p.Questions)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_OpenQuestionId_forQuestion");

            entity.HasOne(d => d.QuestionCategoryIdForQuestionNavigation).WithMany(p => p.Questions)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_QuestionCategoryId_forQuestion");

            entity.HasOne(d => d.QuestionLevelIdForQuestionNavigation).WithMany(p => p.Questions)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_QuestionLevelId_forQuestion");

            entity.HasOne(d => d.QuestionValueIdForQuestionNavigation).WithMany(p => p.Questions)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_QuestionValueId_forQuestion");
        });

        modelBuilder.Entity<QuestionCategory>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Question__3214EC071ACA4029");
        });

        modelBuilder.Entity<QuestionLevel>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Question__3214EC07FED618B1");
        });

        modelBuilder.Entity<QuestionValue>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Question__3214EC07FE18557A");
        });

        modelBuilder.Entity<Sector>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Sector__3214EC076F2194FB");
        });

        modelBuilder.Entity<Vacancy>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Vacancy__3214EC076ECF1F9C");

            entity.HasOne(d => d.DepartmentIdForVacancyNavigation).WithMany(p => p.Vacancies)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_DepartmentId_forVacancy");

            entity.HasOne(d => d.JobDegreeIdForVacancyNavigation).WithMany(p => p.Vacancies)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_JobDegreeId_forVacancy");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}