// <auto-generated />
using System;
using Interview.Persistence.Contexts.InterviewDbContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Interview.Persistence.Migrations.Interview
{
    [DbContext(typeof(InterviewContext))]
    [Migration("20231005160200_InterviewContextMigration")]
    partial class InterviewContextMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Interview.Domain.Entities.Models.Candidate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CandidateDocumentId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__Candidate");

                    b.HasIndex("CandidateDocumentId");

                    b.ToTable("Candidate");
                });

            modelBuilder.Entity("Interview.Domain.Entities.Models.CandidateDocument", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cv")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("CV");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Patronymic")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phonenumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Surname")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id")
                        .HasName("PK__CandidateDocument");

                    b.ToTable("CandidateDocument");
                });

            modelBuilder.Entity("Interview.Domain.Entities.Models.Level", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Coefficient")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Name");

                    b.HasKey("Id")
                        .HasName("PK__Level");

                    b.ToTable("Level");
                });

            modelBuilder.Entity("Interview.Domain.Entities.Models.Position", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id")
                        .HasName("PK__Position");

                    b.ToTable("Position");
                });

            modelBuilder.Entity("Interview.Domain.Entities.Models.Question", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("LevelId")
                        .HasColumnType("int");

                    b.Property<int>("SessionTypeId")
                        .HasColumnType("int");

                    b.Property<int>("StructureId")
                        .HasColumnType("int");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id")
                        .HasName("PK__Question");

                    b.HasIndex("LevelId");

                    b.HasIndex("SessionTypeId");

                    b.HasIndex("StructureId");

                    b.ToTable("Question");
                });

            modelBuilder.Entity("Interview.Domain.Entities.Models.Session", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CandidateId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("EndValue")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("VacancyId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__Session");

                    b.HasIndex("CandidateId");

                    b.HasIndex("VacancyId");

                    b.ToTable("Session");
                });

            modelBuilder.Entity("Interview.Domain.Entities.Models.SessionQuestion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("QuestionId")
                        .HasColumnType("int");

                    b.Property<int>("SessionId")
                        .HasColumnType("int");

                    b.Property<int>("Value")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__SessionQuestion");

                    b.HasIndex("QuestionId");

                    b.HasIndex("SessionId");

                    b.ToTable("SessionQuestion");
                });

            modelBuilder.Entity("Interview.Domain.Entities.Models.SessionType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id")
                        .HasName("PK__SessionType");

                    b.ToTable("SessionType");
                });

            modelBuilder.Entity("Interview.Domain.Entities.Models.Structure", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ParentId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StructureTypeId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__Structure");

                    b.HasIndex("StructureTypeId");

                    b.ToTable("Structure");
                });

            modelBuilder.Entity("Interview.Domain.Entities.Models.StructureType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id")
                        .HasName("PK__StructureType");

                    b.ToTable("StructureType");
                });

            modelBuilder.Entity("Interview.Domain.Entities.Models.Vacancy", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("PositionId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("StructureId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id")
                        .HasName("PK__Vacancy");

                    b.HasIndex("PositionId");

                    b.HasIndex("StructureId");

                    b.ToTable("Vacancy");
                });

            modelBuilder.Entity("Interview.Domain.Entities.Models.Candidate", b =>
                {
                    b.HasOne("Interview.Domain.Entities.Models.CandidateDocument", "CandidateDocument")
                        .WithMany("Candidates")
                        .HasForeignKey("CandidateDocumentId")
                        .IsRequired()
                        .HasConstraintName("FK_CandidateDocument_forCandidates");

                    b.Navigation("CandidateDocument");
                });

            modelBuilder.Entity("Interview.Domain.Entities.Models.Question", b =>
                {
                    b.HasOne("Interview.Domain.Entities.Models.Level", "Level")
                        .WithMany("Questions")
                        .HasForeignKey("LevelId")
                        .IsRequired()
                        .HasConstraintName("FK_LevelId_forQuestion");

                    b.HasOne("Interview.Domain.Entities.Models.SessionType", "SessionType")
                        .WithMany("Questions")
                        .HasForeignKey("SessionTypeId")
                        .IsRequired()
                        .HasConstraintName("FK_SessionTypeId_forQuestion");

                    b.HasOne("Interview.Domain.Entities.Models.Structure", "Structure")
                        .WithMany("Questions")
                        .HasForeignKey("StructureId")
                        .IsRequired()
                        .HasConstraintName("FK_StructureId_forQuestion");

                    b.Navigation("Level");

                    b.Navigation("SessionType");

                    b.Navigation("Structure");
                });

            modelBuilder.Entity("Interview.Domain.Entities.Models.Session", b =>
                {
                    b.HasOne("Interview.Domain.Entities.Models.Candidate", "Candidate")
                        .WithMany("Sessions")
                        .HasForeignKey("CandidateId")
                        .IsRequired()
                        .HasConstraintName("FK_CandidateId_forSession");

                    b.HasOne("Interview.Domain.Entities.Models.Vacancy", "Vacancy")
                        .WithMany("Sessions")
                        .HasForeignKey("VacancyId")
                        .IsRequired()
                        .HasConstraintName("FK_VacancyId_forSession");

                    b.Navigation("Candidate");

                    b.Navigation("Vacancy");
                });

            modelBuilder.Entity("Interview.Domain.Entities.Models.SessionQuestion", b =>
                {
                    b.HasOne("Interview.Domain.Entities.Models.Question", "Question")
                        .WithMany("SessionQuestions")
                        .HasForeignKey("QuestionId")
                        .IsRequired()
                        .HasConstraintName("FK_QuestionId_forSessionQuestion");

                    b.HasOne("Interview.Domain.Entities.Models.Session", "Session")
                        .WithMany("SessionQuestions")
                        .HasForeignKey("SessionId")
                        .IsRequired()
                        .HasConstraintName("FK_SessionId_forSessionQuestion");

                    b.Navigation("Question");

                    b.Navigation("Session");
                });

            modelBuilder.Entity("Interview.Domain.Entities.Models.Structure", b =>
                {
                    b.HasOne("Interview.Domain.Entities.Models.StructureType", "StructureType")
                        .WithMany("Structures")
                        .HasForeignKey("StructureTypeId")
                        .IsRequired()
                        .HasConstraintName("FK_StructureType_forStructure");

                    b.Navigation("StructureType");
                });

            modelBuilder.Entity("Interview.Domain.Entities.Models.Vacancy", b =>
                {
                    b.HasOne("Interview.Domain.Entities.Models.Position", "Position")
                        .WithMany("Vacancies")
                        .HasForeignKey("PositionId")
                        .IsRequired()
                        .HasConstraintName("FK_PositionId_forVacancy");

                    b.HasOne("Interview.Domain.Entities.Models.Structure", "Structure")
                        .WithMany("Vacancies")
                        .HasForeignKey("StructureId")
                        .IsRequired()
                        .HasConstraintName("FK_StructureId_forVacancy");

                    b.Navigation("Position");

                    b.Navigation("Structure");
                });

            modelBuilder.Entity("Interview.Domain.Entities.Models.Candidate", b =>
                {
                    b.Navigation("Sessions");
                });

            modelBuilder.Entity("Interview.Domain.Entities.Models.CandidateDocument", b =>
                {
                    b.Navigation("Candidates");
                });

            modelBuilder.Entity("Interview.Domain.Entities.Models.Level", b =>
                {
                    b.Navigation("Questions");
                });

            modelBuilder.Entity("Interview.Domain.Entities.Models.Position", b =>
                {
                    b.Navigation("Vacancies");
                });

            modelBuilder.Entity("Interview.Domain.Entities.Models.Question", b =>
                {
                    b.Navigation("SessionQuestions");
                });

            modelBuilder.Entity("Interview.Domain.Entities.Models.Session", b =>
                {
                    b.Navigation("SessionQuestions");
                });

            modelBuilder.Entity("Interview.Domain.Entities.Models.SessionType", b =>
                {
                    b.Navigation("Questions");
                });

            modelBuilder.Entity("Interview.Domain.Entities.Models.Structure", b =>
                {
                    b.Navigation("Questions");

                    b.Navigation("Vacancies");
                });

            modelBuilder.Entity("Interview.Domain.Entities.Models.StructureType", b =>
                {
                    b.Navigation("Structures");
                });

            modelBuilder.Entity("Interview.Domain.Entities.Models.Vacancy", b =>
                {
                    b.Navigation("Sessions");
                });
#pragma warning restore 612, 618
        }
    }
}
