// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Interview.Domain.Entities.Base;
using Interview.Domain.Entities.Models;
using Microsoft.EntityFrameworkCore;

namespace Interview.Domain.Entities.IdentityAuth;

[Table("Users")]
public  class User : BaseEntity
{
    [Key]
    [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
    public int Id { get; set; }

    public string UserName { get; set; }

    public string Email { get; set; }

    public string Password { get; set; }

    public string Phonenumber { get; set; }

    public string ConcurrencyStamp { get; set; }

    public string ImagePath { get; set; }

    public string RefreshToken { get; set; }

    public DateTime? RefreshTokenExpiryTime { get; set; }

    [InverseProperty("User")]
    public virtual ICollection<Session> Session { get; set; } = new List<Session>();

    [InverseProperty("User")]
    public virtual ICollection<UserClaim> UserClaim { get; set; } = new List<UserClaim>();

    [InverseProperty("User")]
    public virtual ICollection<UserRole> UserRole { get; set; } = new List<UserRole>();
}