// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Interview.Domain.Entities.Base;
using Microsoft.EntityFrameworkCore;

namespace Interview.Domain.Entities.Models;


[Table("Questions")]
public  class Question : BaseEntity
{
    [Key]
    [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
    public int Id { get; set; }

    [Required]
    public string Text { get; set; }

    public int LevelId { get; set; }

    public int CategoryId { get; set; }

    public int StructureId { get; set; }

    [ForeignKey("CategoryId")]
    [InverseProperty("Question")]
    public virtual Category Category { get; set; }

    [ForeignKey("LevelId")]
    [InverseProperty("Question")]
    public virtual Level Level { get; set; }

    [InverseProperty("Question")]
    public virtual ICollection<SessionQuestion> SessionQuestion { get; set; } = new List<SessionQuestion>();

    [ForeignKey("StructureId")]
    [InverseProperty("Question")]
    public virtual Structure Structure { get; set; }
}