// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Interview.Domain.Entities.Base;
using Microsoft.EntityFrameworkCore;

namespace Interview.Domain.Entities.Models;

[Table("Structures")]
public  class Structure : BaseEntity
{
    [Key]
    [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
    public int Id { get; set; }

    [Required]
    public string Name { get; set; }

    [Required]
    public string ParentId { get; set; }

    public int StructureTypeId { get; set; }

    [InverseProperty("Structure")]
    public virtual ICollection<Question> Question { get; set; } = new List<Question>();

    [ForeignKey("StructureTypeId")]
    [InverseProperty("Structure")]
    public virtual StructureType StructureType { get; set; }

    [InverseProperty("Structure")]
    public virtual ICollection<Vacancy> Vacancy { get; set; } = new List<Vacancy>();
}