// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Interview.Domain.Entities.Base;
using Microsoft.EntityFrameworkCore;

namespace Interview.Domain.Entities.Models;


[Table("Vacancies")]
public  class Vacancy : BaseEntity
{
    [Key]
    [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
    public int Id { get; set; }

    [Required]
    public string Title { get; set; }

    [Required]
    public string Description { get; set; }

    public DateTime StartDate { get; set; }

    public DateTime EndDate { get; set; }

    public int PositionId { get; set; }

    public int StructureId { get; set; }

    [ForeignKey("PositionId")]
    [InverseProperty("Vacancy")]
    public virtual Position Position { get; set; }

    [InverseProperty("Vacancy")]
    public virtual ICollection<Session> Session { get; set; } = new List<Session>();

    [ForeignKey("StructureId")]
    [InverseProperty("Vacancy")]
    public virtual Structure Structure { get; set; }
}