// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Interview.Domain.Entities.Base;
using Microsoft.EntityFrameworkCore;

namespace Interview.Domain.Entities.Models;

[Table("Branch")]
public partial class Branch : BaseEntity
{
    [Key]
    [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
    public int Id { get; set; }

    [Required]
    public string BranchName { get; set; }

    public int SectorId { get; set; }

    [InverseProperty("Branch")]
    public virtual ICollection<Department> Departments { get; set; } = new List<Department>();

    [ForeignKey("SectorId")]
    [InverseProperty("Branches")]
    public virtual Sector Sector { get; set; }
}