// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Interview.Domain.Entities.Base;
using Microsoft.EntityFrameworkCore;

namespace Interview.Domain.Entities.Models;

[Table("Branch")]
public partial class Branch : BaseEntity
{
    [Key]
    [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
    public int IdBranch { get; set; }

    [Required]
    public string BranchName { get; set; }

    [Column("SectorId_forBranch")]
    public int SectorIdForBranch { get; set; }

    [InverseProperty("BranchIdForDepartmentNavigation")]
    public virtual ICollection<Department> Departments { get; set; } = new List<Department>();

    [ForeignKey("SectorIdForBranch")]
    [InverseProperty("Branches")]
    public virtual Sector SectorIdForBranchNavigation { get; set; }
}