// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Interview.Domain.Entities.Base;
using Microsoft.EntityFrameworkCore;

namespace Interview.Domain.Entities.Models;

[Table("CandidateVacancy")]
public partial class CandidateVacancy : BaseEntity
{
    [Key]
    [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
    public int Id { get; set; }

    public int CandidateId { get; set; }

    public int VacancyId { get; set; }

    [ForeignKey("CandidateId")]
    [InverseProperty("CandidateVacancies")]
    public virtual Candidate Candidate { get; set; }

    [ForeignKey("VacancyId")]
    [InverseProperty("CandidateVacancies")]
    public virtual Vacancy Vacancy { get; set; }
}