// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Interview.Domain.Entities.Base;
using Microsoft.EntityFrameworkCore;

namespace Interview.Domain.Entities.Models;

[Table("CandidateQuestion")]
public partial class CandidateQuestion : BaseEntity
{
    [Key]
    [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
    public int IdCandidateQuestion { get; set; }

    [Column("CandidateId_forCandidateQuestion")]
    public int CandidateIdForCandidateQuestion { get; set; }

    [Column("QuestionId_forCandidateQuestion")]
    public int QuestionIdForCandidateQuestion { get; set; }

    [ForeignKey("CandidateIdForCandidateQuestion")]
    [InverseProperty("CandidateQuestions")]
    public virtual Candidate CandidateIdForCandidateQuestionNavigation { get; set; }

    [ForeignKey("QuestionIdForCandidateQuestion")]
    [InverseProperty("CandidateQuestions")]
    public virtual Question QuestionIdForCandidateQuestionNavigation { get; set; }
}