// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Interview.Domain.Entities.Base;
using Microsoft.EntityFrameworkCore;

namespace Interview.Domain.Entities.Models;

[Table("Candidate")]
public partial class Candidate : BaseEntity
{
    [Key]
    [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
    public int Id { get; set; }

    [Required]
    public string CandidateSurname { get; set; }

    [Required]
    public string CandidateName { get; set; }

    [Required]
    public string CandidatePhonenumber { get; set; }

    [Required]
    public string CandidateEmail { get; set; }

    [Required]
    public string CurriculumVitae { get; set; }

    [Required]
    public string Address { get; set; }

    [InverseProperty("Candidate")]
    public virtual ICollection<CandidateQuestion> CandidateQuestions { get; set; } = new List<CandidateQuestion>();

    [InverseProperty("Candidate")]
    public virtual ICollection<CandidateVacancy> CandidateVacancies { get; set; } = new List<CandidateVacancy>();

    [InverseProperty("Candidate")]
    public virtual ICollection<Result> Results { get; set; } = new List<Result>();
}