// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Interview.Domain.Entities.Base;
using Microsoft.EntityFrameworkCore;

namespace Interview.Domain.Entities.Models;

[Table("Candidates")]
public class Candidate : BaseEntity
{
    [Key]
    [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
    public int Id { get; set; }

    public int CandidateDocumentId { get; set; }

    [ForeignKey("CandidateDocumentId")]
    [InverseProperty("Candidate")]
    public virtual CandidateDocument CandidateDocument { get; set; }

    [InverseProperty("Candidate")]
    public virtual ICollection<Session> Session { get; set; } = new List<Session>();
}