// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Interview.Domain.Entities.Base;
using Microsoft.EntityFrameworkCore;

namespace Interview.Domain.Entities.Models;

[Table("CandidateVacancy")]
public partial class CandidateVacancy : BaseEntity
{
    [Key]
    [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
    public int Id { get; set; }

    [Column("CandidateId_forCandidateVacancy")]
    public int CandidateIdForCandidateVacancy { get; set; }

    [Column("VacancyId_forCandidateVacancy")]
    public int VacancyIdForCandidateVacancy { get; set; }

    [ForeignKey("CandidateIdForCandidateVacancy")]
    [InverseProperty("CandidateVacancies")]
    public virtual Candidate CandidateIdForCandidateVacancyNavigation { get; set; }

    [ForeignKey("VacancyIdForCandidateVacancy")]
    [InverseProperty("CandidateVacancies")]
    public virtual Vacancy VacancyIdForCandidateVacancyNavigation { get; set; }
}