// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Interview.Domain.Entities.Base;
using Microsoft.EntityFrameworkCore;

namespace Interview.Domain.Entities.Models;

[Table("Department")]
public partial class Department : BaseEntity
{
    [Key]
    [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
    public int IdDepartment { get; set; }

    [Required]
    public string DepartmentName { get; set; }

    [Column("BranchId_forDepartment")]
    public int BranchIdForDepartment { get; set; }

    [ForeignKey("BranchIdForDepartment")]
    [InverseProperty("Departments")]
    public virtual Branch BranchIdForDepartmentNavigation { get; set; }

    [InverseProperty("DepartmentIdForVacancyNavigation")]
    public virtual ICollection<Vacancy> Vacancies { get; set; } = new List<Vacancy>();
}