// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Interview.Domain.Entities.Base;
using Microsoft.EntityFrameworkCore;

namespace Interview.Domain.Entities.Models;

[Table("Question")]
public partial class Question : BaseEntity
{
    [Key]
    [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
    public int Id { get; set; }

    public int QuestionSessionId { get; set; }

    public int QuestionValueId { get; set; }

    public int QuestionLevelId { get; set; }

    public int QuestionCategoryId { get; set; }

    [InverseProperty("Question")]
    public virtual ICollection<CandidateQuestion> CandidateQuestions { get; set; } = new List<CandidateQuestion>();

    [ForeignKey("QuestionCategoryId")]
    [InverseProperty("Questions")]
    public virtual QuestionCategory QuestionCategory { get; set; }

    [ForeignKey("QuestionLevelId")]
    [InverseProperty("Questions")]
    public virtual QuestionLevel QuestionLevel { get; set; }

    [ForeignKey("QuestionSessionId")]
    [InverseProperty("Questions")]
    public virtual QuestionSession QuestionSession { get; set; }

    [ForeignKey("QuestionValueId")]
    [InverseProperty("Questions")]
    public virtual QuestionValue QuestionValue { get; set; }
}