// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Interview.Domain.Entities.Base;
using Microsoft.EntityFrameworkCore;

namespace Interview.Domain.Entities.Models;

[Table("Question")]
public partial class Question : BaseEntity
{
    [Key]
    [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
    public int Id { get; set; }

    [Column("OpenQuestionId_forQuestion")]
    public int OpenQuestionIdForQuestion { get; set; }

    [Column("QuestionValueId_forQuestion")]
    public int QuestionValueIdForQuestion { get; set; }

    [Column("QuestionLevelId_forQuestion")]
    public int QuestionLevelIdForQuestion { get; set; }

    [Column("QuestionCategoryId_forQuestion")]
    public int QuestionCategoryIdForQuestion { get; set; }

    [InverseProperty("QuestionIdForCandidateQuestionNavigation")]
    public virtual ICollection<CandidateQuestion> CandidateQuestions { get; set; } = new List<CandidateQuestion>();

    [ForeignKey("OpenQuestionIdForQuestion")]
    [InverseProperty("Questions")]
    public virtual OpenQuestion OpenQuestionIdForQuestionNavigation { get; set; }

    [ForeignKey("QuestionCategoryIdForQuestion")]
    [InverseProperty("Questions")]
    public virtual QuestionCategory QuestionCategoryIdForQuestionNavigation { get; set; }

    [ForeignKey("QuestionLevelIdForQuestion")]
    [InverseProperty("Questions")]
    public virtual QuestionLevel QuestionLevelIdForQuestionNavigation { get; set; }

    [ForeignKey("QuestionValueIdForQuestion")]
    [InverseProperty("Questions")]
    public virtual QuestionValue QuestionValueIdForQuestionNavigation { get; set; }
}