// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Interview.Domain.Entities.Base;
using Microsoft.EntityFrameworkCore;

namespace Interview.Domain.Entities.Models;

[Table("QuestionValue")]
public partial class QuestionValue : BaseEntity
{
    [Key]
    [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
    public int Id { get; set; }

    [Column("QuestionValue")]
    public int QuestionValue1 { get; set; }

    [InverseProperty("QuestionValueIdForQuestionNavigation")]
    public virtual ICollection<Question> Questions { get; set; } = new List<Question>();
}