// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Interview.Domain.Entities.Base;
using Microsoft.EntityFrameworkCore;

namespace Interview.Domain.Entities.Models;

[Table("Question")]
public partial class Question : BaseEntity
{
    [Key]
    [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
    public int Id { get; set; }

    [Required]
    public string QuestionTitle { get; set; }

    [Required]
    public string QuestionText { get; set; }

    public int LevelId { get; set; }

    public int CategoryId { get; set; }

    [InverseProperty("Question")]
    public virtual ICollection<CandidateQuestion> CandidateQuestions { get; set; } = new List<CandidateQuestion>();

    [ForeignKey("CategoryId")]
    [InverseProperty("Questions")]
    public virtual Category Category { get; set; }

    [ForeignKey("LevelId")]
    [InverseProperty("Questions")]
    public virtual Level Level { get; set; }

    [InverseProperty("Question")]
    public virtual ICollection<Session> Sessions { get; set; } = new List<Session>();
}