// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Interview.Domain.Entities.Base;
using Microsoft.EntityFrameworkCore;

namespace Interview.Domain.Entities.Models;

[Table("Sector")]
public partial class Sector : BaseEntity
{
    [Key]
    [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
    public int IdSector { get; set; }

    [Required]
    public string SectorName { get; set; }

    [InverseProperty("SectorIdForBranchNavigation")]
    public virtual ICollection<Branch> Branches { get; set; } = new List<Branch>();
}