// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Interview.Domain.Entities.Base;
using Microsoft.EntityFrameworkCore;

namespace Interview.Domain.Entities.Models;

[Table("Session")]
public partial class Session : BaseEntity
{
    [Key]
    [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
    public int Id { get; set; }

    public DateTime? SessionTime { get; set; }

    public int QuestionId { get; set; }

    public int ValueId { get; set; }

    [ForeignKey("QuestionId")]
    [InverseProperty("Sessions")]
    public virtual Question Question { get; set; }

    [ForeignKey("ValueId")]
    [InverseProperty("Sessions")]
    public virtual Value Value { get; set; }
}