// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Interview.Domain.Entities.Base;
using Microsoft.EntityFrameworkCore;

namespace Interview.Domain.Entities.Models;

[Table("Session")]
public class Session : BaseEntity
{
    [Key]
    [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
    public int Id { get; set; }

    [Column(TypeName = "decimal(18, 4)")]
    public decimal EndValue { get; set; }

    public DateTime? StartDate { get; set; }

    public DateTime? EndDate { get; set; }

    public int VacancyId { get; set; }

    public int CandidateId { get; set; }

    [ForeignKey("CandidateId")]
    [InverseProperty("Sessions")]
    public virtual Candidate Candidate { get; set; }

    [InverseProperty("Session")]
    public virtual ICollection<SessionQuestion> SessionQuestions { get; set; } = new List<SessionQuestion>();

    [ForeignKey("VacancyId")]
    [InverseProperty("Sessions")]
    public virtual Vacancy Vacancy { get; set; }
}