// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Interview.Domain.Entities.Base;
using Microsoft.EntityFrameworkCore;

namespace Interview.Domain.Entities.Models;

[Table("Vacancy")]
public partial class Vacancy : BaseEntity
{
    [Key]
    [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
    public int Id { get; set; }

    [Required]
    public string Title { get; set; }

    [Required]
    public string Description { get; set; }

    [Column("JobDegreeId_forVacancy")]
    public int JobDegreeIdForVacancy { get; set; }

    [Column("DepartmentId_forVacancy")]
    public int DepartmentIdForVacancy { get; set; }

    [InverseProperty("VacancyIdForCandidateVacancyNavigation")]
    public virtual ICollection<CandidateVacancy> CandidateVacancies { get; set; } = new List<CandidateVacancy>();

    [ForeignKey("DepartmentIdForVacancy")]
    [InverseProperty("Vacancies")]
    public virtual Department DepartmentIdForVacancyNavigation { get; set; }

    [ForeignKey("JobDegreeIdForVacancy")]
    [InverseProperty("Vacancies")]
    public virtual JobDegree JobDegreeIdForVacancyNavigation { get; set; }
}