// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Interview.Domain.Entities.Base;
using Microsoft.EntityFrameworkCore;

namespace Interview.Domain.Entities.Models;

[Table("Vacancy")]
public partial class Vacancy : BaseEntity
{
    [Key]
    [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
    public int Id { get; set; }

    [Required]
    public string Title { get; set; }

    [Required]
    public string Description { get; set; }

    public int JobDegreeId { get; set; }

    public int SectorId { get; set; }

    [InverseProperty("Vacancy")]
    public virtual ICollection<CandidateVacancy> CandidateVacancies { get; set; } = new List<CandidateVacancy>();

    [ForeignKey("JobDegreeId")]
    [InverseProperty("Vacancies")]
    public virtual JobDegree JobDegree { get; set; }

    [ForeignKey("SectorId")]
    [InverseProperty("Vacancies")]
    public virtual Sector Sector { get; set; }
}